apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop-dev
  region: us-east-1
managedNodeGroups:
- name: roboshop-nodes
  desiredCapacity: 2  # This is 3 by default
  instanceTypes: ["m5.large", "t3.large", "t3.small", "c5.large"]
